// examples/vue/src/App.vue
<script setup lang="ts">
import { ref, reactive, toRefs, onMounted, nextTick } from 'vue'
import { PasskeyManager, type PasskeyManagerConfigs } from '@tatchi-xyz/sdk'
import { usePostfixPosition } from './composables/usePostfixPosition'
import AccountDetails from './components/AccountDetails.vue'
import Toast, { notify as notifyToast } from './components/Toast.vue'

const relayerUrl = import.meta.env.VITE_RELAYER_URL || 'https://relay-server.localhost'
const walletOrigin = import.meta.env.VITE_WALLET_ORIGIN || 'https://wallet.example.localhost'

const ACCOUNT_DOMAIN = 'w3a-v1.testnet'

const config: PasskeyManagerConfigs = {
  nearNetwork: 'testnet',
  nearRpcUrl: 'https://test.rpc.fastnear.com',
  contractId: ACCOUNT_DOMAIN,
  relayer: { accountId: ACCOUNT_DOMAIN, url: relayerUrl },
  iframeWallet: { walletOrigin, sdkBasePath: '/sdk' },
}

const pm = new PasskeyManager(config)

// Group UI state into a single reactive object to reduce boilerplate
const state = reactive<{
  username: string
  waiting: boolean
  iframeReady: boolean
  isLoggedIn: boolean
  currentAccount: string | null
  loginDetails: any | null
}>({
  username: '',
  waiting: false,
  iframeReady: false,
  isLoggedIn: false,
  currentAccount: null,
  loginDetails: null,
})

const { username, waiting, iframeReady, isLoggedIn, currentAccount, loginDetails } = toRefs(state)

const postfixText = `.${ACCOUNT_DOMAIN}`
// Postfix overlay positioning
const { inputRef, postfixRef, scheduleMeasure } = usePostfixPosition(username)

onMounted(async () => {
  try {
    await pm.initWalletIframe() // establish iframe client when walletOrigin is set
    iframeReady.value = !!pm.getWalletIframeClient()?.isReady()
  } catch (e) { console.warn('[vue] iframe init warn:', e) }
  try {
    const st = await pm.getLoginState()
    isLoggedIn.value = !!st.vrfActive
    currentAccount.value = st.nearAccountId || null
    loginDetails.value = st as any
    // Prefill input with recent account username (without ".${ACCOUNT_DOMAIN}")
    if (!username.value && st.nearAccountId) {
      const suffix = `.${ACCOUNT_DOMAIN}`
      const acct = st.nearAccountId
      const base = acct.endsWith(suffix) ? acct.slice(0, -suffix.length) : acct
      username.value = base
      await nextTick()
      try { scheduleMeasure() } catch {}
    }
  } catch {}
})

async function register() {
  const id = username.value.trim()
  if (!id) return
  const fullId = `${id}.${ACCOUNT_DOMAIN}`
  waiting.value = true
  notifyToast('Starting registration…')
  try {
    const res = await pm.registerPasskey(fullId, {
      onEvent: (ev) => { notifyToast(`${ev.phase ?? ev.step}: ${ev.message}`) },
      onError: (err) => { notifyToast(err.message || String(err), 'error') },
    })
    if (res?.success) {
      notifyToast('Registered successfully', 'success')
      const st = await pm.getLoginState(fullId)
      isLoggedIn.value = !!st.vrfActive
      currentAccount.value = fullId
      loginDetails.value = st as any
    } else {
      notifyToast(res?.error || 'Registration failed', 'error')
    }
  } catch (e: any) {
    notifyToast(e?.message || String(e), 'error')
  } finally {
    waiting.value = false
  }
}

async function login() {
  const id = username.value.trim()
  if (!id) return
  const fullId = `${id}.${ACCOUNT_DOMAIN}`
  waiting.value = true
  notifyToast('Starting login…')
  try {
    const res = await pm.loginPasskey(fullId, {
      onEvent: (ev) => { notifyToast(`${ev.phase ?? ev.step}: ${ev.message}`) },
      onError: (err) => { notifyToast(err.message || String(err), 'error') },
    })
    if (res?.success) {
      notifyToast('Logged in successfully', 'success')
      const st = await pm.getLoginState(fullId)
      isLoggedIn.value = !!st.vrfActive
      currentAccount.value = fullId
      loginDetails.value = st as any
    } else {
      notifyToast(res?.error || 'Login failed', 'error')
    }
  } catch (e: any) {
    notifyToast(e?.message || String(e), 'error')
  } finally {
    waiting.value = false
  }
}
</script>

<template>
  <main class="app-main">
    <h1>Vue Tatchi Passkey Example</h1>
    <p>Wallet iframe runs on <code>{{ walletOrigin }}</code></p>
    <p>Ensure your dev server sets Permissions-Policy and CSP headers in vite.config.ts with the tatchiHeaders() plugin.</p>
    <br/>
    <h2>Tatchi Status</h2>
    <ul>
      <li>iframe ready: <strong>{{ iframeReady }}</strong></li>
      <li>logged in: <strong>{{ isLoggedIn }}</strong></li>
      <li v-if="currentAccount">recent account: <strong>{{ currentAccount }}</strong></li>
    </ul>

    <AccountDetails v-if="isLoggedIn && loginDetails" :details="loginDetails" :fallback-account="currentAccount" />

    <div class="actions">
      <div class="input-wrap">
        <input
          ref="inputRef"
          v-model="username"
          placeholder="alice"
          class="username"
          @input="scheduleMeasure"
        />
        <span ref="postfixRef" class="postfix">
          {{ postfixText }}
        </span>
      </div>
      <button :disabled="waiting || !username" @click="register" class="btn">
        {{ waiting ? 'Registering…' : 'Register' }}
      </button>
      <button :disabled="waiting || !username" @click="login" class="btn">
        {{ waiting ? 'Logging in…' : 'Login' }}
      </button>
    </div>

    <Toast />
  </main>

  <footer class="app-footer">
    <a href="https://tatchi.xyz" target="_blank">tatchi.xyz</a>
  </footer>
</template>

<style scoped>
.app-main {
  padding: 24px;
  font-family: system-ui, Arial, sans-serif;
}

h1 { font-size: 1.5rem; }
h2 { font-size: 1.25rem; }

.actions {
  margin-top: 16px;
  display: flex;
  gap: 8px;
  align-items: center;
}

.input-wrap {
  position: relative;
  display: inline-block;
}

.username {
  padding: 8px 10px;
  border: 1px solid #ccc;
  border-radius: 6px;
  min-width: 200px;
}

.postfix {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  color: #888;
  white-space: pre;
  visibility: hidden;
  pointer-events: none;
}

.btn {
  padding: 8px 12px;
  border-radius: 6px;
}

.app-footer {
  padding: 16px;
  color: #666;
}
</style>

// examples/svelte/src/App.svelte
<script lang="ts">
  import { onMount, tick } from 'svelte'
  import { PasskeyManager, type PasskeyManagerConfigs } from '@tatchi-xyz/sdk'
  import AccountDetails from './components/AccountDetails.svelte'
  import Toast from './components/Toast.svelte'

  const relayerUrl = import.meta.env.VITE_RELAYER_URL || 'https://relay-server.localhost'
  const walletOrigin = import.meta.env.VITE_WALLET_ORIGIN || 'https://wallet.example.localhost'

  const ACCOUNT_DOMAIN = 'w3a-v1.testnet'

  const config: PasskeyManagerConfigs = {
    nearNetwork: 'testnet',
    nearRpcUrl: 'https://test.rpc.fastnear.com',
    contractId: ACCOUNT_DOMAIN,
    relayer: { accountId: ACCOUNT_DOMAIN, url: relayerUrl },
    iframeWallet: { walletOrigin, sdkBasePath: '/sdk' },
  }

  const pm = new PasskeyManager(config)
  let username = ''
  let waiting = false
  let lastEvent = ''
  let iframeReady = false
  let isLoggedIn = false
  let currentAccount: string | null = null
  let loginDetails: any | null = null

  // Toast state
  let toastVisible = false
  let toastMessage = ''
  let toastType: 'info' | 'success' | 'warning' | 'error' = 'info'
  let toastTimer: any = null

  function clearToastTimer() { if (toastTimer) { clearTimeout(toastTimer); toastTimer = null } }
  function notify(msg: string, severity: 'info' | 'success' | 'warning' | 'error' | 'warn' = 'info', life = 3500) {
    lastEvent = msg
    toastMessage = msg
    toastType = (severity === 'warn' ? 'warning' : severity) as any
    toastVisible = true
    clearToastTimer()
    if (life > 0) toastTimer = setTimeout(() => { toastVisible = false }, life)
  }

  // Postfix overlay positioning
  const postfixText = `.${ACCOUNT_DOMAIN}`
  let inputRef: HTMLInputElement | null = null
  let postfixRef: HTMLSpanElement | null = null
  let ctx: CanvasRenderingContext2D | null = null

  function measureAndPosition() {
    const input = inputRef
    const postfix = postfixRef
    if (!input || !postfix) return
    const value = (username || '')
    if (!value) {
      postfix.style.visibility = 'hidden'
      postfix.style.left = '0px'
      return
    }
    if (!ctx) { const c = document.createElement('canvas'); ctx = c.getContext('2d') }
    const cs = window.getComputedStyle(input)
    const font = cs.font && cs.font !== ''
      ? cs.font
      : `${cs.fontStyle || ''} ${cs.fontVariant || ''} ${cs.fontWeight || ''} ${cs.fontSize || '16px'} / ${cs.lineHeight || 'normal'} ${cs.fontFamily || 'sans-serif'}`
    if (ctx) ctx.font = font
    const text = value
    let width = ctx ? ctx.measureText(text).width : (text.length * 8)
    const letterSpacing = parseFloat(cs.letterSpacing || '0') || 0
    if (letterSpacing !== 0 && text.length > 1) width += letterSpacing * (text.length - 1)
    const padLeft = (parseFloat(cs.paddingLeft || '0') || 0) + (parseFloat(cs.borderLeftWidth || '0') || 0)
    postfix.style.left = `${Math.ceil(padLeft + width + 1)}px`
    postfix.style.visibility = 'visible'
  }
  function scheduleMeasure() { requestAnimationFrame(() => requestAnimationFrame(measureAndPosition)) }

  // React when username changes
  $: username, scheduleMeasure()

  onMount(async () => {
    try {
      await pm.initWalletIframe()
      iframeReady = !!pm.getWalletIframeClient()?.isReady()
    } catch (e) { console.warn('[svelte] iframe init warn:', e) }
    try {
      const st = await pm.getLoginState()
      isLoggedIn = !!st.vrfActive
      currentAccount = st.nearAccountId || null
      loginDetails = st as any
      // Prefill input with recent account username (strip .ACCOUNT_DOMAIN)
      if (!username && st.nearAccountId) {
        const suffix = `.${ACCOUNT_DOMAIN}`
        const acct = st.nearAccountId
        const base = acct.endsWith(suffix) ? acct.slice(0, -suffix.length) : acct
        username = base
        await tick()
        scheduleMeasure()
      }
    } catch {}
    window.addEventListener('resize', scheduleMeasure)
  })

  async function register() {
    const id = (username || '').trim()
    if (!id) return
    const fullId = `${id}.${ACCOUNT_DOMAIN}`
    waiting = true
    notify('Starting registration…')
    try {
      const res = await pm.registerPasskey(fullId, {
        onEvent: (ev) => { notify(`${ev.phase ?? ev.step}: ${ev.message}`) },
        onError: (err) => { notify(err.message || String(err), 'error') },
      })
      if (res?.success) {
        notify('Registered successfully', 'success')
        const st = await pm.getLoginState(fullId)
        isLoggedIn = !!st.vrfActive
        currentAccount = fullId
        loginDetails = st as any
      } else {
        notify(res?.error || 'Registration failed', 'error')
      }
    } catch (e: any) {
      notify(e?.message || String(e), 'error')
    } finally {
      waiting = false
    }
  }

  async function login() {
    const id = (username || '').trim()
    if (!id) return
    const fullId = `${id}.${ACCOUNT_DOMAIN}`
    waiting = true
    notify('Starting login…')
    try {
      const res = await pm.loginPasskey(fullId, {
        onEvent: (ev) => { notify(`${ev.phase ?? ev.step}: ${ev.message}`) },
        onError: (err) => { notify(err.message || String(err), 'error') },
      })
      if (res?.success) {
        notify('Logged in successfully', 'success')
        const st = await pm.getLoginState(fullId)
        isLoggedIn = !!st.vrfActive
        currentAccount = fullId
        loginDetails = st as any
      } else {
        notify(res?.error || 'Login failed', 'error')
      }
    } catch (e: any) {
      notify(e?.message || String(e), 'error')
    } finally {
      waiting = false
    }
  }
</script>

<main class="app-main">
  <h1>Svelte Tatchi Passkey Example</h1>
  <p>Wallet iframe runs on <code>{walletOrigin}</code></p>
  <p>Ensure your dev server sets Permissions-Policy and CSP headers in vite.config.ts with the tatchiHeaders() plugin.</p>
  <br/>
  <h2>Tatchi Status</h2>
  <ul>
    <li>iframe ready: <strong>{String(iframeReady)}</strong></li>
    <li>logged in: <strong>{String(isLoggedIn)}</strong></li>
    {#if currentAccount}<li>recent account: <strong>{currentAccount}</strong></li>{/if}
  </ul>

  {#if isLoggedIn && loginDetails}
    <AccountDetails details={loginDetails} fallbackAccount={currentAccount} />
  {/if}

  <div class="actions">
    <div class="input-wrap">
      <input
        bind:this={inputRef}
        bind:value={username}
        placeholder="alice"
        class="username"
        on:input={scheduleMeasure}
      />
      <span bind:this={postfixRef} class="postfix">{postfixText}</span>
    </div>
    <button class="btn" disabled={waiting || !username} on:click={register}>
      {waiting ? 'Registering…' : 'Register'}
    </button>
    <button class="btn" disabled={waiting || !username} on:click={login}>
      {waiting ? 'Logging in…' : 'Login'}
    </button>
  </div>

  <Toast visible={toastVisible} message={toastMessage} type={toastType} />
</main>

<footer class="app-footer">
  <a href="https://tatchi.xyz" target="_blank">tatchi.xyz</a>
</footer>

<style>
  .app-main { padding: 24px; }

  h1 { font-size: 1.5rem; }
  h2 { font-size: 1.25rem; }

  .actions {
    margin-top: 16px;
    display: flex;
    gap: 8px;
    align-items: center;
  }

  .input-wrap { position: relative; display: inline-block; }

  .username {
    padding: 8px 10px;
    border: 1px solid #ccc;
    border-radius: 6px;
    min-width: 200px;
  }

  .postfix {
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
    color: #888;
    white-space: pre;
    visibility: hidden;
    pointer-events: none;
  }

  .btn { padding: 8px 12px; border-radius: 6px; }

  .app-footer { padding: 16px; color: #666; }
</style>
